# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kustaurant' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kustaurant
  pod 'NMapsMap'
  pod 'naveridlogin-sdk-ios'

  target 'KustaurantTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
